export { default as GitHub } from './GitHub.tsx'
export { default as LinkedIn } from './LinkedIn.tsx'
export { default as Instagram } from './Instagram.tsx'
export { default as X } from './X.tsx'
export { default as LeetCode } from './LeetCode.tsx'
export { default as CodeForces } from './CodeForces.tsx'
